REMARK*CARACTPER-010.WS.v.0002.
      ******************************************************************
      * DLM0002    | CQ3990 - Banco Pichincha . CAST 172.              *
      * 02-ENE-2012|    REQ. CQ. 3990.                                 *
      * DARIO LASSO|                                                   *
      ******************************************************************
CQ3990 01  PERSONALIZACION-10.                                          DLM0002
CQ3990   03  PER-10-NIVEL-00-NUM.                                       DLM0002
CQ3990     05  00NUM999RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00NUM998RO01010         PIC  9(04).                      DLM0002
CQ3990   03  PER-10-NIVEL-01-NUM.                                       DLM0002
CQ3990     05  01NUM999RO01010         PIC  9(04).                      DLM0002
CQ3990     05  01NUM998RO01010         PIC  9(04).                      DLM0002
CQ3990*                                                                 DLM0002
CQ3990   03  PER-10-NIVEL-00-END.                                       DLM0002
CQ3990     05  00END999RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END998RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END997RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END996RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END995RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END994RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END993RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END992RO01010         PIC  9(04).                      DLM0002
CQ3990     05  00END991HP010           PIC  9(04).                      DLM0002
CQ3990     05  00END991IN010           PIC  9(04).                      DLM0002
CQ3990     05  00END991RO010           PIC  9(04).                      DLM0002
CQ3990     05  00END991VE010           PIC  9(04).                      DLM0002
CQ3990     05  00END990HP010           PIC  9(04).                      DLM0002
CQ3990     05  00END990IN010           PIC  9(04).                      DLM0002
CQ3990     05  00END990RO010           PIC  9(04).                      DLM0002
CQ3990     05  00END990VE010           PIC  9(04).                      DLM0002
CQ3990     05  00END989HP010           PIC  9(04).                      DLM0002
CQ3990     05  00END989IN010           PIC  9(04).                      DLM0002
CQ3990     05  00END989RO010           PIC  9(04).                      DLM0002
CQ3990     05  00END989VE010           PIC  9(04).                      DLM0002
CQ3990     05  00END988HP010           PIC  9(04).                      DLM0002
CQ3990     05  00END988IN010           PIC  9(04).                      DLM0002
CQ3990     05  00END988RO010           PIC  9(04).                      DLM0002
CQ3990     05  00END988VE010           PIC  9(04).                      DLM0002
CQ3990   03  PER-10-NIVEL-01-END.                                       DLM0002
CQ3990     05  01END999RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END998RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END997RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END996RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END995RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END994RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END993RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END992RO01010         PIC  9(11).                      DLM0002
CQ3990     05  01END991HP010           PIC  9(11).                      DLM0002
CQ3990     05  01END991IN010           PIC  9(11).                      DLM0002
CQ3990     05  01END991RO010           PIC  9(11).                      DLM0002
CQ3990     05  01END991VE010           PIC  9(11).                      DLM0002
CQ3990     05  01END990HP010           PIC  9(11).                      DLM0002
CQ3990     05  01END990IN010           PIC  9(11).                      DLM0002
CQ3990     05  01END990RO010           PIC  9(11).                      DLM0002
CQ3990     05  01END990VE010           PIC  9(11).                      DLM0002
CQ3990     05  01END989HP010           PIC  9(11).                      DLM0002
CQ3990     05  01END989IN010           PIC  9(11).                      DLM0002
CQ3990     05  01END989RO010           PIC  9(11).                      DLM0002
CQ3990     05  01END989VE010           PIC  9(11).                      DLM0002
CQ3990     05  01END988HP010           PIC  9(11).                      DLM0002
CQ3990     05  01END988IN010           PIC  9(11).                      DLM0002
CQ3990     05  01END988RO010           PIC  9(11).                      DLM0002
CQ3990     05  01END988VE010           PIC  9(11).                      DLM0002
CQ3990*                                                                 DLM0002
CQ3990   03  PER-10-NIVEL-02-END.                                       DLM0002
CQ3990     05  02END991TO010           PIC  9(11).                      DLM0002
CQ3990     05  02END990TO010           PIC  9(11).                      DLM0002
CQ3990     05  02END989TO010           PIC  9(11).                      DLM0002
CQ3990     05  02END988TO010           PIC  9(11).                      DLM0002
CQ3990*                                                                 DLM0002
