      *FRADSU.v01.001.
BDU001*----------------------------------------------------------------*ABB0001
BDU001*ESTRUCTURA DE ARCHIVO DE DATOS SUSCRIPTOR PARA CARGUE EN FRABDU *ABB0001
BDU001*----------------------------------------------------------------*ABB0001
BDU001     SELECT ARC-PLA                                               ABB0001
BDU001            ASSIGN TO DISK ARC-PLA-TITLE                          ABB0001
BDU001            ORGANIZATION IS LINE SEQUENTIAL                       ABB0001
BDU001            ACCESS  MODE IS SEQUENTIAL                            ABB0001
BDU001            FILE STATUS IS STATUS-ARC-PLA.                        ABB0001
