REMARK* FRAOPT-FS.v.0001
REMARK******************************************************************
REMARK* ESTRUCTURA DEL ARCHIVO QUE CONTIENE LAS TABLAS DEL OPTIMIZADOR  
REMARK* PARA GENERAR PREGUNTAS                                         
REMARK******************************************************************
           SELECT FRAOPT      
                  ASSIGN TO DISK TITLE-FRAOPT
                  ORGANIZATION IS LINE SEQUENTIAL.
