      * EST040.v.02.003
      * TABLA DE PRODUCTOS UTILIZADOS EN EL ICGCON
REMARK*****************************************************************
REMARK* GJC0003        *
REMARK* ABRIL DE 2005  * EL NOMBRE LOGICO DEL ARCHIVO CAMBIA DE ABD10
REMARK* G.JIMENEZ      * A ICBPRO PARA CONSERVAR ESTANDARES
REAMRK*****************************************************************
PRODUC     SELECT ICBPRO   ASSIGN TO DISK TITLE-ICBPRO                  GJC0003
PRODUC           ORGANIZATION IS LINE SEQUENTIAL.                       GJC0003
