******* EST012.v.02.003
******* ARCHIVO MAESTRO ENTREGADO POR EL SUSCRIPTOR EN EL MES                
******* INMEDIATAMENTE ANTERIOR AL DEL ULTIMO MES REPORTADO
005215************************************************************
005600     SELECT OPTIONAL ANTERI ASSIGN TO DISK 
000000                                 NOMBRE-1
                  ORGANIZATION IS LINE SEQUENTIAL
                  ACCESS MODE IS SEQUENTIAL.
005215************************************************************
