******* EST011.v.03.001
REMARK* MAESTRO DEL MES ACTUAL ENTREGADO POR UN SUSCRIPTOR EN PARTICULAR
REMARK* PARA REPORTE DE CUENTAS CORRIENTES
005205************************************************************
005700     SELECT ACTUAL1 ASSIGN TO DISK NOMBRE-2
                  ORGANIZATION IS LINE SEQUENTIAL
                  ACCESS MODE IS SEQUENTIAL.
005215************************************************************
