REMARK* PESCODV.FS.V.01.0001
REMARK******************************************************************
REMARK* ESTE ARCHIVO CONTIENE LOS CAMPOS DEL LOG DE LOS PROGRAMAS:     *
REMARK* ICGD49-ICGD22-ICGD12-ICGD40-ICGD25-ICGD60                      *
REMARK******************************************************************
           SELECT PARAMDAVI    ASSIGN TO  ARCHIVO-PARAMDAVI
                  ORGANIZATION         IS  LINE SEQUENTIAL
                  ACCESS MODE          IS  SEQUENTIAL
                  FILE STATUS          IS  W-STATUS-DAV1.
