REMARK* VALCAMCL-FS.v.0001
REMARK******************************************************************
REMARK* TABLA PARAMETROS CAMPOS DEL MAESTRO DE CLIENTES                *
REMARK******************************************************************
           SELECT VALCAMCL ASSIGN TO DISK NOMBRE-VALCAMCL
                           ORGANIZATION IS LINE SEQUENTIAL
                           ACCESS MODE IS SEQUENTIAL.